apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    client.knative.dev/user-image: gcr.io/cool-ml-demos/salesassist-receiver:latest
  labels:
    cloud.googleapis.com/location: us-east1
  name: salesassist-receiver
  namespace: '411150075841'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '20'
        run.googleapis.com/client-name: cloud-console
      name: salesassist-receiver
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: PROJECTIDDATA
          value: cool-ml-demos
        - name: PROJECTIDASSIST
          value: salesassist-help
        - name: TOPICID
          value: sales-assist
        image: gcr.io/cool-ml-demos/salesassist-receiver:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
      serviceAccountName: 411150075841-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
